routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/food', 'HomeController@food');
Route::get('/drink', 'HomeController@drink');
Route::get('/about', 'HomeController@about');
Route::get('/contact', 'HomeController@contact');
Route::get('/food/cari', 'HomeController@cari')->name('cari');
Route::get('/detail/{slug}', 'HomeController@detail')->name('detail');


Route::prefix('admin')
    ->namespace('Admin')->middleware(['auth', 'admin'])
    ->group(function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::resource("food", "FoodController");

        Route::resource("drink", "DrinkController");
    });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/pages/admin/create_food.blade.php
@extends('layouts.admin')

@section('active')

  <li class="nav-item ">
    <a class="nav-link" href="{{ url('/admin') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

  <li class="nav-item active">
    <a class="nav-link" href="{{ route('food.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Makanan</span></a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('drink.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Minuman</span></a>
  </li>
    
@endsection

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Makanan</h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('food.index') }}">Makanan</a></li>
                <li class="breadcrumb-item active" aria-current="page">Tambah</li>
            </ol>
        </nav>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-body">
                    <form enctype="multipart/form-data" class="form-horizontal"
                        action="{{route('food.store')}}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="input_text">Nama Makanan</label>
                                <input type="text" class="form-control" id="food_name" name="food_name"
                                    placeholder="ex : Mie Kocok" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="harga_produk">Daerah Asal</label>
                                <input type="text" class="form-control" id="region" name="region"
                                    placeholder="Bandung" required>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_textarea">Deskripsi</label>
                                <textarea class="form-control" id="description" name="description" rows="3" required></textarea>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_file">Masukkan Foto</label><br>
                                <div class="input-group mb-3 col-md-12">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Upload</span>
                                    </div>
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="picture"
                                            name="picture" required>
                                        <label class="custom-file-label" for="input_picture">Pilih Foto</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_file">Link Video</label><br>
                                <input type="text" class="form-control" id="video" name="video"
                                    placeholder="ex : https://youtube.com/xxx" required>
                            </div>
                            <button type="submit" class="btn btn-primary col-12">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@endsection

resources/views/pages/admin/dashboard.blade.php
@extends('layouts.admin')

@section('active')

  <li class="nav-item active">
    <a class="nav-link" href="{{ url('/admin') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('food.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Makanan</span></a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('drink.index') }}">
        <i class="fas fa-fw fa-water"></i>
        <span>Minuman</span></a>
  </li>
    
@endsection

@section('content')
    <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
          </div>

          <!-- Content Row -->
          <div class="row">

            <!-- Earnings (Monthly) Card Example -->
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1 ">Total Makanan</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800 ">{{ $foods }}</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1 ">Total Minuman</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800 ">{{ $drinks }}</div>
                    </div>
                    <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    <!-- /.container-fluid -->
@endsection

resources/views/pages/admin/edit_food.blade.php
@extends('layouts.admin')

@section('active')

  <li class="nav-item ">
    <a class="nav-link" href="{{ url('/admin') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

  <li class="nav-item active">
    <a class="nav-link" href="{{ route('food.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Makanan</span></a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('drink.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Minuman</span></a>
  </li>
    
@endsection

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Ubah Makanan</h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{route('food.index')}}">Makanan</a></li>
                <li class="breadcrumb-item active" aria-current="page">Ubah</li>
            </ol>
        </nav>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-body">
                    <form enctype="multipart/form-data" class="form-horizontal"
                        action="{{route('food.update',$item->id)}}" method="POST">
                        @method('put')
                        @csrf
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="input_text">Nama Makanan</label>
                                <input type="text" class="form-control" id="food_name" name="food_name"
                                    placeholder="ex : tenderloin" value="{{ $item->food_name }}">
                            </div>
                            <div class="form-group col-md-6">
                                <label for="harga_produk">Daerah Asal</label>
                                <input type="text" class="form-control" id="region" name="region"
                                    placeholder="Bandung" required value="{{ $item->region }}">
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_textarea">Deskripsi</label>
                                <textarea class="form-control" id="description" name="description"
                                    rows="3">{{ $item->description }}</textarea>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_picture">Masukkan Foto</label><br>
                                <div class="input-group mb-3 col-md-12">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Upload</span>
                                    </div>
                                    <div class="custom-file">
                                        <input type="file" accept="image/*" class="custom-file-input" id="picture"
                                        name="picture">
                                        <label class="custom-file-label" for="input_picture">Pilih Foto</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_file">Link Video</label><br>
                                <input type="text" class="form-control" id="video" name="video"
                                    placeholder="ex : https://youtube.com/xxx" required value="{{ $item->video }}"> 
                            </div>
                            <button type="submit" class="btn btn-primary col-12">Ubah</button>
                            <a href="{{ route('food.index') }}"
                                class="btn btn-danger col-12 mt-1">Batalkan</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@endsection

resources/views/pages/admin/food.blade.php
@extends('layouts.admin')

@section('active')

  <li class="nav-item ">
    <a class="nav-link" href="{{ url('/admin') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

  <li class="nav-item active">
    <a class="nav-link" href="{{ route('food.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Makanan</span></a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('drink.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Minuman</span></a>
  </li>
    
@endsection

@section('content')
    
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Daftar Makanan</h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Makanan</li>
            </ol>
        </nav>
    </div>

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a href="{{ route('food.create') }}" class="btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-plus fa-sm text-white-50"></i> Tambah Makanan
        </a>
    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="example" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Makanan</th>
                            <th>Khas Daerah</th>
                            {{-- <th>Deskripsi</th> --}}
                            <th>Video</th>
                            <th>Foto</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($foods as $item)
                        <tr>
                            <td>{{$item->food_name}}</td>
                            <td>{{$item->region}}</td>
                            {{-- <td>
                                @php
                                    $first = strtok($item->description, '.');
                                    echo $first;
                                @endphp    
                            </td> --}}
                            <td>{{$item->video}}</td>
                            <td>
                                @if ($item->picture)
                                <img src="{{ asset('uploads/food/' . $item->picture) }}" class="img-fluid"
                                    alt="" width="100%">
                                @endif
                            </td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <div class="col-md-6 mt-2">

                                        <a href="{{ route('food.edit',$item->id) }}"
                                            class="btn btn-primary " >
                                            Ubah
                                        </a>

                                    </div>
                                    <div class="col-md-6 mt-2">
                                        <button class="btn btn-danger" data-toggle="modal" data-id="{{ $item->id }}"
                                            data-target="#deleteModal">
                                            Hapus
                                        </button>
                                    </div>

                                    <!-- Delete Modal-->
                                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
                                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Hapus Makanan</h5>
                                                    <button class="close" type="button" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">Apakah anda yakin ingin menghapusnya?</div>
                                                <div class="modal-footer">
                                                    <button class="btn btn-secondary" type="button"
                                                        data-dismiss="modal">Batal</button>
                                                    <form action="{{ route('food.destroy',$item->id) }}"
                                                        method="POST" class="delete">
                                                        @csrf
                                                        @method('delete')
                                                        <input type="hidden" name="id" id="input-id">
                                                        <button class="btn btn-primary btn-delete">Hapus</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

@endsection