routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/food', 'HomeController@food');
Route::get('/drink', 'HomeController@drink');
Route::get('/about', 'HomeController@about');
Route::get('/contact', 'HomeController@contact');
Route::get('/food/cari', 'HomeController@cari')->name('cari');
Route::get('/detail/{slug}', 'HomeController@detail')->name('detail');


Route::prefix('admin')
    ->namespace('Admin')->middleware(['auth', 'admin'])
    ->group(function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::resource("food", "FoodController");

        Route::resource("drink", "DrinkController");
    });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Drink.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Drink extends Model
{
    use SoftDeletes;
}

app/Http/Controllers/Admin/DrinkController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Drink;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class DrinkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['drinks'] = Drink::all();
        return view('pages.admin.drink.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.admin.drink.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'drink_name', 'region',  'picture', 'description', 'video' => 'required',
        ]);

        $drink = new Drink();
        $drink->drink_name = $request->drink_name;
        $drink->region = $request->region;
        $drink->video = $request->video;
        $drink->description = $request->description;
        $drink->slug = Str::slug($request->drink_name, '-');

        if ($request->file('picture')) {
            $fileGet = $request->picture;
            $fileName = $fileGet->getClientOriginalName();

            $fileExtension1 = substr($fileName, -4);
            $fileExtension2 = substr($fileName, -5);

            if ($fileExtension1 == ".jpg" || $fileExtension1 == ".png" || $fileExtension2 == ".jpeg") {
                $move = $fileGet->move('uploads/drink', $fileName);
                $drink->picture = $fileName;

                $drink->save();
                alert()->success('Sukses !', 'Minuman Ditambahkan.');
                return redirect()->route('drink.index');
            } else {
                alert()->error("Error !", 'Masukkan File Gambar Yang Sesuai!');
                return redirect()->route('drink.create');
            }
        }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Drink::findOrFail($id);

        return view(
            'pages.admin.drink.edit',
            [
                'item' => $item
            ],
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $slug = Str::slug($request->drink_name, '-');
        if (!empty($request->file('picture'))){

            if ($request->file('picture')) {
                $fileGet = $request->picture;
                $fileName = $fileGet->getClientOriginalName();
    
                $fileExtension1 = substr($fileName, -4);
                $fileExtension2 = substr($fileName, -5);
    
                if ($fileExtension1 == ".jpg" || $fileExtension1 == ".png" || $fileExtension2 == ".jpeg") {
                    $move = $fileGet->move('uploads/drink', $fileName);
                    Drink::where('id', $id)
                        ->update([

                            'picture' => $fileName,
                            'drink_name' => $request->drink_name,
                            'region' => $request->region,
                            'description' => $request->description,
                            'video' => $request->video,
                            'slug' => $slug

                        ]);
                    alert()->success('Sukses !', 'Minuman Diubah.');
                    return redirect()->route('drink.index');
                } else {
                    alert()->error("Error !", 'Masukkan File Gambar Yang Sesuai!');
                    return redirect()->route('drink.edit',$id);
                }
            }
        }
        else{
            Drink::where('id', $id)
            ->update([
                'drink_name' => $request->drink_name,
                'region' => $request->region,
                'description' => $request->description,
                'video' => $request->video,
                'slug' => $slug
            ]);
            alert()->success('Sukses !', 'Minuman Diubah.');
            return redirect()->route('drink.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $product = Drink::findOrFail($request->id);
        $product->delete();
        alert()->success('Sukses !', 'Minuman Berhasil dihapus.');
        return redirect()->route('drink.index');
    }
}

resources/views/pages/admin/drink/create.blade.php
@extends('layouts.admin')

@section('active')

  <li class="nav-item ">
    <a class="nav-link" href="{{ url('/admin') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

  <li class="nav-item ">
    <a class="nav-link" href="{{ route('food.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Makanan</span></a>
  </li>

  <li class="nav-item active">
    <a class="nav-link" href="{{ route('drink.index') }}">
        <i class="fas fa-glass-cheers"></i>
        <span>Minuman</span></a>
  </li>
    
@endsection

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Tambah Minuman</h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('drink.index') }}">Minuman</a></li>
                <li class="breadcrumb-item active" aria-current="page">Tambah</li>
            </ol>
        </nav>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-body">
                    <form enctype="multipart/form-data" class="form-horizontal"
                        action="{{route('drink.store')}}" method="POST">
                        @csrf
                        <div class="row">
                             <div class="form-group col-md-6">
                                <label for="input_text">Nama Minuman</label>
                                <input type="text" class="form-control" id="drink_name" name="drink_name"
                                    placeholder="ex : Es Cendol" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="harga_produk">Daerah Asal</label>
                                <input type="text" class="form-control" id="region" name="region"
                                    placeholder="ex : Bandung" required>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_textarea">Deskripsi</label>
                                <textarea class="form-control" id="description" name="description" rows="3" required></textarea>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_file">Masukkan Foto</label><br>
                                <div class="input-group mb-3 col-md-12">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Upload</span>
                                    </div>
                                    <div class="custom-file">
                                        <input type="file" accept="image/*" class="custom-file-input" id="picture"
                                            name="picture" required>
                                        <label class="custom-file-label" for="input_picture">Pilih Foto</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_file">Link Video</label><br>
                                <input type="text" class="form-control" id="video" name="video"
                                    placeholder="ex : https://youtube.com/xxx" required>
                            </div>
                            <button type="submit" class="btn btn-primary col-12">Simpan</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@endsection

resources/views/pages/admin/drink/edit.blade.php
@extends('layouts.admin')

@section('active')

  <li class="nav-item ">
    <a class="nav-link" href="{{ url('/admin') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

  <li class="nav-item ">
    <a class="nav-link" href="{{ route('food.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Makanan</span></a>
  </li>

  <li class="nav-item active">
    <a class="nav-link" href="{{ route('drink.index') }}">
        <i class="fas fa-glass-cheers"></i>
        <span>Minuman</span></a>
  </li>
    
@endsection

@section('content')
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit Minuman</h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{ route('drink.index') }}">Minuman</a></li>
                <li class="breadcrumb-item active" aria-current="page">Ubah</li>
            </ol>
        </nav>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-body">
                    <form enctype="multipart/form-data" class="form-horizontal"
                        action="{{route('drink.update',$item->id)}}" method="POST">
                        @method('put')
                        @csrf
                        <div class="row">
                             <div class="form-group col-md-6">
                                <label for="input_text">Nama Minuman</label>
                                <input type="text" class="form-control" id="drink_name" name="drink_name"
                                    value="{{$item->drink_name}}" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label for="harga_produk">Daerah Asal</label>
                                <input type="text" class="form-control" id="region" name="region"
                                   value="{{$item->region}}" required>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_textarea">Deskripsi</label>
                                <textarea class="form-control" id="description" name="description" rows="3"  required>{{$item->description}}</textarea>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_file">Masukkan Foto</label><br>
                                <div class="input-group mb-3 col-md-12">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Upload</span>
                                    </div>
                                    <div class="custom-file">
                                        <input type="file" accept="image/*" class="custom-file-input" id="picture"
                                            name="picture">
                                        <label class="custom-file-label" for="input_picture">Pilih Foto</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <label for="input_file">Link Video</label><br>
                                <input type="text" class="form-control" id="video" name="video"
                                   value="{{ $item->video }}" required>
                            </div>
                            <button type="submit" class="btn btn-primary col-12">Ubah</button>
                            <a href="{{ route('drink.index') }}"
                                class="btn btn-danger col-12 mt-1">Batalkan</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
@endsection

resources/views/pages/admin/drink/index.blade.php
@extends('layouts.admin')

@section('active')

  <li class="nav-item ">
    <a class="nav-link" href="{{ url('/admin') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

  <li class="nav-item">
    <a class="nav-link" href="{{ route('food.index') }}">
        <i class="fas fa-fw fa-utensils"></i>
        <span>Makanan</span></a>
  </li>

  <li class="nav-item active">
    <a class="nav-link" href="{{ route('drink.index') }}">
        <i class="fas fa-glass-cheers"></i>
        <span>Minuman</span></a>
  </li>
    
@endsection

@section('content')
    
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Daftar Minuman</h1>
        <nav aria-label="breadcrumb text-right">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item active" aria-current="page">Minuman</li>
            </ol>
        </nav>
    </div>

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <a href="{{ route('drink.create') }}" class="btn btn-sm btn-primary shadow-sm">
            <i class="fas fa-plus fa-sm text-white-50"></i> Tambah Minuman
        </a>
    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="example" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Minuman</th>
                            <th>Khas Daerah</th>
                            {{-- <th>Deskripsi</th> --}}
                            <th>Video</th>
                            <th>Foto</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                       @foreach ($drinks as $item)
                        <tr>
                            <td>{{$item->drink_name}}</td>
                            <td>{{$item->region}}</td>
                            {{-- <td>
                                @php
                                    $first = strtok($item->description, '.');
                                    echo $first;
                                @endphp    
                            </td> --}}
                            <td>{{$item->video}}</td>
                            <td>
                                @if ($item->picture)
                                <img src="{{ asset('uploads/drink/' . $item->picture) }}" class="img-fluid"
                                    alt="" width="100%">
                                @endif
                            </td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <div class="col-md-6 mt-2">

                                        <a href="{{ route('drink.edit',$item->id) }}"
                                            class="btn btn-primary " >
                                            Ubah
                                        </a>

                                    </div>
                                    <div class="col-md-6 mt-2">
                                        <button class="btn btn-danger" data-toggle="modal" data-id="{{ $item->id }}"
                                            data-target="#deleteModal">
                                            Hapus
                                        </button>
                                    </div>

                                    <!-- Delete Modal-->
                                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog"
                                        aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Hapus Makanan</h5>
                                                    <button class="close" type="button" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">×</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">Apakah anda yakin ingin menghapusnya?</div>
                                                <div class="modal-footer">
                                                    <button class="btn btn-secondary" type="button"
                                                        data-dismiss="modal">Batal</button>
                                                    <form action="{{ route('drink.destroy',$item->id) }}"
                                                        method="POST" class="delete">
                                                        @csrf
                                                        @method('delete')
                                                        <input type="hidden" name="id" id="input-id">
                                                        <button class="btn btn-primary btn-delete">Hapus</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach 
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

@endsection